# -*- coding: utf-8 -*-
"""Hackathon3_QCM_Tech.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cBS_OCdl9p05601xgp-YBONkP08YRlqr

#SQL
"""

SQL_0 ={
  "QCM_SQL_debutant": {
    "1": {
      "Question": "Quelle commande SQL est utilisée pour extraire des données d'une base de données ?",
      "A": "SELECT",
      "B": "GET",
      "C": "EXTRACT",
      "D": "RETRIEVE",
      "Reponse": "A"
    },
    "2": {
      "Question": "Quelle commande SQL est utilisée pour mettre à jour des données dans une base de données ?",
      "A": "MODIFY",
      "B": "SAVE",
      "C": "UPDATE",
      "D": "INSERT",
      "Reponse": "C"
    },
    "3": {
      "Question": "Quelle commande SQL est utilisée pour supprimer des données d'une base de données ?",
      "A": "DELETE",
      "B": "REMOVE",
      "C": "DROP",
      "D": "CLEAR",
      "Reponse": "A"
    },
    "4": {
      "Question": "Comment sélectionner toutes les colonnes d'une table nommée 'employees' ?",
      "A": "SELECT ALL FROM employees;",
      "B": "SELECT * FROM employees;",
      "C": "SELECT employees;",
      "D": "SELECT ALL COLUMNS FROM employees;",
      "Reponse": "B"
    },
    "5": {
      "Question": "Quelle commande SQL est utilisée pour ajouter une nouvelle table à une base de données ?",
      "A": "INSERT TABLE",
      "B": "ADD TABLE",
      "C": "NEW TABLE",
      "D": "CREATE TABLE",
      "Reponse": "D"
    },
    "6": {
      "Question": "Quelle commande SQL est utilisée pour ajouter de nouvelles données à une table ?",
      "A": "INSERT INTO",
      "B": "ADD DATA",
      "C": "ADD INTO",
      "D": "INSERT NEW",
      "Reponse": "A"
    },
    "7": {
      "Question": "Comment filtrer les résultats d'une requête pour ne montrer que les enregistrements où la colonne 'age' est supérieure à 30 ?",
      "A": "SELECT * FROM table WHERE age > 30;",
      "B": "SELECT * FROM table FILTER age > 30;",
      "C": "SELECT * FROM table HAVING age > 30;",
      "D": "SELECT * FROM table WHERE age IS OVER 30;",
      "Reponse": "A"
    },
    "8": {
      "Question": "Quelle clause SQL est utilisée pour trier les résultats d'une requête ?",
      "A": "ORDER BY",
      "B": "SORT BY",
      "C": "GROUP BY",
      "D": "ARRANGE BY",
      "Reponse": "A"
    },
    "9": {
      "Question": "Quelle commande SQL est utilisée pour supprimer une table existante dans une base de données ?",
      "A": "DROP TABLE",
      "B": "DELETE TABLE",
      "C": "REMOVE TABLE",
      "D": "CLEAR TABLE",
      "Reponse": "A"
    },
    "10": {
      "Question": "Comment limiter le nombre de résultats retournés par une requête SQL à 10 enregistrements ?",
      "A": "SELECT * FROM table LIMIT 10;",
      "B": "SELECT * FROM table STOP AT 10;",
      "C": "SELECT TOP 10 FROM table;",
      "D": "SELECT FIRST 10 FROM table;",
      "Reponse": "A"
    }
  }
}

SQL_2 ={
  "QCM_SQL_intermediaire": {
    "1": {
      "Question": "Comment sélectionner uniquement les enregistrements uniques dans une colonne 'email' de la table 'users' ?",
      "A": "SELECT UNIQUE email FROM users;",
      "B": "SELECT DISTINCT email FROM users;",
      "C": "SELECT DIFFERENT email FROM users;",
      "D": "SELECT SINGLE email FROM users;",
      "Reponse": "B"
    },
    "2": {
      "Question": "Comment ajouter une colonne 'age' de type INTEGER à une table 'employees' ?",
      "A": "ALTER TABLE employees ADD COLUMN age INTEGER;",
      "B": "MODIFY TABLE employees ADD COLUMN age INTEGER;",
      "C": "UPDATE TABLE employees ADD age INTEGER;",
      "D": "ALTER employees ADD age INTEGER;",
      "Reponse": "A"
    },
    "3": {
      "Question": "Quelle commande est utilisée pour récupérer les données d'une table en les triant par la colonne 'name' en ordre décroissant ?",
      "A": "SELECT * FROM table ORDER BY name DESC;",
      "B": "SELECT * FROM table SORT BY name DESC;",
      "C": "SELECT * FROM table ORDER name DESC;",
      "D": "SELECT * FROM table SORT name DESC;",
      "Reponse": "A"
    },
    "4": {
      "Question": "Quelle clause est utilisée pour filtrer les résultats d'une requête SQL en fonction d'une condition ?",
      "A": "WHERE",
      "B": "FILTER",
      "C": "HAVING",
      "D": "CONDITION",
      "Reponse": "A"
    },
    "5": {
      "Question": "Comment trouver le salaire moyen des employés par département dans une table 'employees' ?",
      "A": "SELECT department, AVG(salary) FROM employees GROUP BY department;",
      "B": "SELECT department, AVERAGE(salary) FROM employees GROUP BY department;",
      "C": "SELECT department, MEAN(salary) FROM employees GROUP BY department;",
      "D": "SELECT department, AVG(salary) FROM employees;",
      "Reponse": "A"
    },
    "6": {
      "Question": "Quelle commande est utilisée pour combiner les résultats de deux requêtes SQL ?",
      "A": "UNION",
      "B": "COMBINE",
      "C": "JOIN",
      "D": "MERGE",
      "Reponse": "A"
    },
    "7": {
      "Question": "Comment sélectionner tous les employés dont le salaire est compris entre 3000 et 5000 ?",
      "A": "SELECT * FROM employees WHERE salary >= 3000 AND salary <= 5000;",
      "B": "SELECT * FROM employees WHERE salary BETWEEN 3000 AND 5000;",
      "C": "SELECT * FROM employees WHERE salary >= 3000 TO 5000;",
      "D": "SELECT * FROM employees WHERE salary IN RANGE 3000 TO 5000;",
      "Reponse": "B"
    },
    "8": {
      "Question": "Comment trouver le nombre total d'employés dans chaque département ?",
      "A": "SELECT department, COUNT(*) FROM employees GROUP BY department;",
      "B": "SELECT department, SUM(*) FROM employees GROUP BY department;",
      "C": "SELECT department, TOTAL(*) FROM employees GROUP BY department;",
      "D": "SELECT department, NUMBER(*) FROM employees GROUP BY department;",
      "Reponse": "A"
    },
    "9": {
      "Question": "Quelle commande SQL est utilisée pour insérer des données dans une table ?",
      "A": "INSERT INTO",
      "B": "ADD INTO",
      "C": "INSERT TO",
      "D": "ADD TO",
      "Reponse": "A"
    },
    "10": {
      "Question": "Comment sélectionner les employés dont le nom commence par 'J' ?",
      "A": "SELECT * FROM employees WHERE name LIKE 'J%';",
      "B": "SELECT * FROM employees WHERE name LIKE '%J';",
      "C": "SELECT * FROM employees WHERE name = 'J%';",
      "D": "SELECT * FROM employees WHERE name STARTS WITH 'J';",
      "Reponse": "A"
    }
  }
}

SQL_3 ={
  "QCM_SQL_confirme": {
    "1": {
      "Question": "Comment écrire une requête SQL pour trouver les employés ayant le salaire le plus élevé dans chaque département ?",
      "A": "SELECT department, MAX(salary) FROM employees GROUP BY department;",
      "B": "SELECT department, MAX(salary) FROM employees;",
      "C": "SELECT department, salary FROM employees GROUP BY department HAVING MAX(salary);",
      "D": "SELECT department, MAX(salary) FROM employees GROUP BY salary;",
      "Reponse": "A"
    },
    "2": {
      "Question": "Quelle commande SQL est utilisée pour modifier une colonne existante dans une table ?",
      "A": "ALTER TABLE",
      "B": "MODIFY TABLE",
      "C": "CHANGE TABLE",
      "D": "UPDATE TABLE",
      "Reponse": "A"
    },
    "3": {
      "Question": "Comment écrire une requête SQL pour supprimer les doublons d'une table 'employees' en se basant sur la colonne 'email' ?",
      "A": "DELETE FROM employees WHERE email NOT IN (SELECT DISTINCT email FROM employees);",
      "B": "DELETE FROM employees WHERE email IN (SELECT DISTINCT email FROM employees);",
      "C": "DELETE DUPLICATE email FROM employees;",
      "D": "DELETE FROM employees WHERE email DUPLICATE;",
      "Reponse": "A"
    },
    "4": {
      "Question": "Quelle est la différence entre 'INNER JOIN' et 'LEFT JOIN' en SQL ?",
      "A": "INNER JOIN retourne les lignes communes aux deux tables ; LEFT JOIN retourne toutes les lignes de la table de gauche et les lignes correspondantes de la table de droite.",
      "B": "INNER JOIN retourne toutes les lignes des deux tables ; LEFT JOIN retourne uniquement les lignes de la table de gauche.",
      "C": "INNER JOIN retourne les lignes communes aux deux tables ; LEFT JOIN retourne uniquement les lignes de la table de droite.",
      "D": "INNER JOIN et LEFT JOIN sont équivalents.",
      "Reponse": "A"
    },
    "5": {
      "Question": "Comment écrire une requête SQL pour mettre à jour le salaire des employés du département 'Sales' à 5000 ?",
      "A": "UPDATE employees SET salary = 5000 WHERE department = 'Sales';",
      "B": "MODIFY employees SET salary = 5000 WHERE department = 'Sales';",
      "C": "UPDATE employees CHANGE salary TO 5000 WHERE department = 'Sales';",
      "D": "SET employees.salary = 5000 WHERE department = 'Sales';",
      "Reponse": "A"
    },
    "6": {
      "Question": "Comment écrire une requête SQL pour récupérer les cinq premiers enregistrements d'une table 'employees' ?",
      "A": "SELECT * FROM employees LIMIT 5;",
      "B": "SELECT * FROM employees TOP 5;",
      "C": "SELECT FIRST 5 FROM employees;",
      "D": "SELECT * FROM employees FIRST 5;",
      "Reponse": "A"
    },
    "7": {
      "Question": "Comment écrire une requête SQL pour trouver le nombre d'employés dans chaque département qui ont un salaire supérieur à 4000 ?",
      "A": "SELECT department, COUNT(*) FROM employees WHERE salary > 4000 GROUP BY department;",
      "B": "SELECT department, COUNT(*) FROM employees GROUP BY department WHERE salary > 4000;",
      "C": "SELECT department, SUM(*) FROM employees WHERE salary > 4000 GROUP BY department;",
      "D": "SELECT department, COUNT(*) WHERE salary > 4000 FROM employees GROUP BY department;",
      "Reponse": "A"
    },
    "8": {
      "Question": "Comment écrire une requête SQL pour récupérer les employés dont le nom contient 'Smith' ?",
      "A": "SELECT * FROM employees WHERE name LIKE '%Smith%';",
      "B": "SELECT * FROM employees WHERE name = 'Smith';",
      "C": "SELECT * FROM employees WHERE name CONTAINS 'Smith';",
      "D": "SELECT * FROM employees WHERE name LIKE 'Smith';",
      "Reponse": "A"
    },
    "9": {
      "Question": "Quelle est la commande SQL pour ajouter une contrainte UNIQUE à une colonne 'email' existante dans une table 'users' ?",
      "A": "ALTER TABLE users ADD CONSTRAINT unique_email UNIQUE (email);",
      "B": "MODIFY TABLE users ADD UNIQUE (email);",
      "C": "ALTER TABLE users ADD UNIQUE (email);",
      "D": "UPDATE TABLE users ADD CONSTRAINT UNIQUE (email);",
      "Reponse": "A"
    },
    "10": {
      "Question": "Comment écrire une requête SQL pour calculer la somme des salaires par département ?",
      "A": "SELECT department, SUM(salary) FROM employees GROUP BY department;",
      "B": "SELECT department, TOTAL(salary) FROM employees GROUP BY department;",
      "C": "SELECT department, ADD(salary) FROM employees GROUP BY department;",
      "D": "SELECT department, SUM(salary) FROM employees;",
      "Reponse": "A"
    }
  }
}

"""#Python"""

Python_1={
  "QCM_python_debutant": {
    "1": {
      "Question": "Quelle est la sortie de `print('Hello, World!')` en Python ?",
      "A": "Hello World!",
      "B": "Hello, World!",
      "C": "print('Hello, World!')",
      "D": "'Hello, World!'",
      "Reponse": "B"
    },
    "2": {
      "Question": "Quelle est la bonne syntaxe pour créer une fonction en Python ?",
      "A": "def ma_fonction():",
      "B": "function ma_fonction():",
      "C": "create ma_fonction():",
      "D": "func ma_fonction():",
      "Reponse": "A"
    },
    "3": {
      "Question": "Comment insérer un commentaire en Python ?",
      "A": "// ceci est un commentaire",
      "B": "/* ceci est un commentaire */",
      "C": "# ceci est un commentaire",
      "D": "-- ceci est un commentaire",
      "Reponse": "C"
    },
    "4": {
      "Question": "Quelle est la sortie de `print(2 + 2)` ?",
      "A": "22",
      "B": "4",
      "C": "2 + 2",
      "D": "Erreur",
      "Reponse": "B"
    },
    "5": {
      "Question": "Quelle est la bonne syntaxe pour une boucle 'for' en Python ?",
      "A": "for x in range(6):",
      "B": "for x to 6:",
      "C": "for x range(6):",
      "D": "for x in 6:",
      "Reponse": "A"
    },
    "6": {
      "Question": "Comment créer une liste en Python ?",
      "A": "ma_liste = []",
      "B": "ma_liste = {}",
      "C": "ma_liste = ()",
      "D": "ma_liste = <>",
      "Reponse": "A"
    },
    "7": {
      "Question": "Comment ajouter un élément à une liste en Python ?",
      "A": "ma_liste.add('élément')",
      "B": "ma_liste.append('élément')",
      "C": "ma_liste.insert('élément')",
      "D": "ma_liste.push('élément')",
      "Reponse": "B"
    },
    "8": {
      "Question": "Quelle méthode est utilisée pour renvoyer la longueur d'une liste en Python ?",
      "A": "len()",
      "B": "length()",
      "C": "count()",
      "D": "size()",
      "Reponse": "A"
    },
    "9": {
      "Question": "Quelle méthode est utilisée pour supprimer l'espace de début et de fin d'une chaîne en Python ?",
      "A": "trim()",
      "B": "strip()",
      "C": "cut()",
      "D": "remove()",
      "Reponse": "B"
    },
    "10": {
      "Question": "Comment vérifier si une clé existe dans un dictionnaire en Python ?",
      "A": "if 'clé' in dictionnaire:",
      "B": "if dictionnaire.has('clé'):",
      "C": "if 'clé' exist in dictionnaire:",
      "D": "if dictionnaire.contains('clé'):",
      "Reponse": "A"
    }
  }
}

Python_2={
  "QCM_python_intermediaire": {
    "1": {
      "Question": "Quelle est la sortie de `print(list(map(lambda x: x*2, [1, 2, 3, 4])))` ?",
      "A": "[2, 4, 6, 8]",
      "B": "[1, 4, 6, 8]",
      "C": "[1, 2, 3, 4]",
      "D": "Erreur",
      "Reponse": "A"
    },
    "2": {
      "Question": "Comment ouvrir un fichier nommé 'example.txt' en mode lecture en Python ?",
      "A": "open('example.txt', 'r')",
      "B": "open('example.txt', 'w')",
      "C": "open('example.txt')",
      "D": "open('example.txt', 'a')",
      "Reponse": "A"
    },
    "3": {
      "Question": "Quelle est la sortie de `print(2 ** 3)` ?",
      "A": "6",
      "B": "8",
      "C": "9",
      "D": "Erreur",
      "Reponse": "B"
    },
    "4": {
      "Question": "Comment vérifier si tous les éléments d'une liste 'ma_liste' sont vrais ?",
      "A": "all(ma_liste)",
      "B": "every(ma_liste)",
      "C": "check(ma_liste)",
      "D": "validate(ma_liste)",
      "Reponse": "A"
    },
    "5": {
      "Question": "Quelle est la sortie de `print('Hello, {}'.format('World'))` ?",
      "A": "Hello, {}",
      "B": "Hello, World",
      "C": "Hello, format",
      "D": "Erreur",
      "Reponse": "B"
    },
    "6": {
      "Question": "Comment inverser une liste nommée 'ma_liste' ?",
      "A": "ma_liste.reverse()",
      "B": "ma_liste[::-1]",
      "C": "ma_liste.invert()",
      "D": "reverse(ma_liste)",
      "Reponse": "A"
    },
    "7": {
      "Question": "Comment vérifier si une chaîne 'abc' est dans une chaîne 'texte' ?",
      "A": "'abc' in texte",
      "B": "'abc' dans texte",
      "C": "'abc' includes texte",
      "D": "'abc' contain texte",
      "Reponse": "A"
    },
    "8": {
      "Question": "Comment diviser une chaîne 'texte' en une liste de sous-chaînes en utilisant l'espace comme séparateur ?",
      "A": "texte.split(' ')",
      "B": "texte.split('')",
      "C": "texte.split()",
      "D": "texte.divide(' ')",
      "Reponse": "A"
    },
    "9": {
      "Question": "Quelle est la sortie de `print([x for x in range(5) if x % 2 == 0])` ?",
      "A": "[0, 1, 2, 3, 4]",
      "B": "[1, 3]",
      "C": "[0, 2, 4]",
      "D": "Erreur",
      "Reponse": "C"
    },
    "10": {
      "Question": "Quelle méthode est utilisée pour créer un dictionnaire à partir de deux listes en Python ?",
      "A": "dict(zip(liste1, liste2))",
      "B": "dictionary(liste1, liste2)",
      "C": "zip(liste1, liste2)",
      "D": "map(liste1, liste2)",
      "Reponse": "A"
    }
  }
}

Python_3={
  "QCM_python_confirme": {
    "1": {
      "Question": "Quelle est la sortie de `print([i for i in range(10) if i % 2 == 0])` en Python ?",
      "A": "[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]",
      "B": "[2, 4, 6, 8, 10]",
      "C": "[0, 2, 4, 6, 8]",
      "D": "[1, 3, 5, 7, 9]",
      "Reponse": "C"
    },
    "2": {
      "Question": "Comment gérer les exceptions en Python ?",
      "A": "try-except",
      "B": "try-catch",
      "C": "try-handle",
      "D": "try-rescue",
      "Reponse": "A"
    },
    "3": {
      "Question": "Quelle est la sortie de `print([x ** 2 for x in range(10) if x % 2 == 0])` ?",
      "A": "[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]",
      "B": "[0, 4, 16, 36, 64]",
      "C": "[1, 9, 25, 49, 81]",
      "D": "[0, 2, 4, 6, 8]",
      "Reponse": "B"
    },
    "4": {
      "Question": "Quelle est la fonction utilisée pour créer une copie profonde (deep copy) d'un objet 'obj' en Python ?",
      "A": "copy.deepcopy(obj)",
      "B": "obj.copy()",
      "C": "deep.copy(obj)",
      "D": "obj.deep_copy()",
      "Reponse": "A"
    },
    "5": {
      "Question": "Comment ouvrir une connexion à une base de données SQLite nommée 'database.db' en utilisant le module 'sqlite3' en Python ?",
      "A": "conn = sqlite3.connect('database.db')",
      "B": "connection.open('database.db')",
      "C": "conn.open('database.db')",
      "D": "connection = sqlite3('database.db')",
      "Reponse": "A"
    },
    "6": {
      "Question": "Quelle est la méthode utilisée pour trier une liste 'liste' en utilisant une fonction de tri personnalisée en Python ?",
      "A": "liste.sort(key=lambda x: x)",
      "B": "liste.sorted(lambda x: x)",
      "C": "sort(liste, key=lambda x: x)",
      "D": "sorted(liste, key=lambda x: x)",
      "Reponse": "D"
    },
    "7": {
      "Question": "Comment définir une classe nommée 'Personne' avec les attributs 'nom' et 'âge' en Python ?",
      "A": "class Personne: def __init__(self, nom, âge): self.nom = nom self.âge = âge",
      "B": "class Personne: __init__(self, nom, âge): self.nom = nom self.âge = âge",
      "C": "class Personne: def __init__(self, nom, âge): self.nom = nom; self.âge = âge",
      "D": "class Personne: def init(self, nom, âge): self.nom = nom self.âge = âge",
      "Reponse": "A"
    },
    "8": {
      "Question": "Quelle méthode est utilisée pour gérer des erreurs dans Python ?",
      "A": "try-except",
      "B": "try-catch",
      "C": "try-error",
      "D": "try-fail",
      "Reponse": "A"
    },
    "9": {
      "Question": "Comment supprimer tous les éléments d'une liste 'liste' en Python ?",
      "A": "liste.clear()",
      "B": "delete liste",
      "C": "liste.delete()",
      "D": "del liste",
      "Reponse": "A"
    },
    "10": {
      "Question": "Quelle est la fonction utilisée pour obtenir le chemin absolu du répertoire courant en Python ?",
      "A": "os.getcwd()",
      "B": "getcwd()",
      "C": "current.path()",
      "D": "path.get_current()",
      "Reponse": "A"
    }
  }
}

"""#PowerBi"""

PowerBi_1={
  "QCM_PowerBI_debutant": {
    "1": {
      "Question": "Quel est le principal logiciel utilisé pour créer des rapports Power BI ?",
      "A": "Power BI Desktop",
      "B": "Power BI Service",
      "C": "Power BI Mobile",
      "D": "Power BI Server",
      "Reponse": "A"
    },
    "2": {
      "Question": "Quel type de fichier est généralement utilisé pour enregistrer un rapport Power BI Desktop ?",
      "A": ".pbix",
      "B": ".xlsx",
      "C": ".csv",
      "D": ".docx",
      "Reponse": "A"
    },
    "3": {
      "Question": "Quelle fonctionnalité de Power BI permet de combiner plusieurs sources de données ?",
      "A": "Power Query",
      "B": "Power Pivot",
      "C": "Power View",
      "D": "Power Map",
      "Reponse": "A"
    },
    "4": {
      "Question": "Quelle visualisation est utilisée pour représenter des données hiérarchiques sous forme de branches d'arbre ?",
      "A": "Tree Map",
      "B": "Bar Chart",
      "C": "Pie Chart",
      "D": "Line Chart",
      "Reponse": "A"
    },
    "5": {
      "Question": "Quelle est la fonction DAX utilisée pour calculer la somme d'une colonne ?",
      "A": "SUM",
      "B": "TOTAL",
      "C": "COUNT",
      "D": "AGGREGATE",
      "Reponse": "A"
    },
    "6": {
      "Question": "Quelle visualisation est la meilleure pour montrer la tendance de données sur une période de temps ?",
      "A": "Line Chart",
      "B": "Pie Chart",
      "C": "Tree Map",
      "D": "Scatter Plot",
      "Reponse": "A"
    },
    "7": {
      "Question": "Quel est l'outil utilisé pour rédiger des expressions DAX dans Power BI ?",
      "A": "DAX Editor",
      "B": "Query Editor",
      "C": "Report Editor",
      "D": "Model Editor",
      "Reponse": "A"
    },
    "8": {
      "Question": "Quelle option permet de filtrer les données au niveau visuel dans Power BI ?",
      "A": "Visual Level Filters",
      "B": "Page Level Filters",
      "C": "Report Level Filters",
      "D": "Data Level Filters",
      "Reponse": "A"
    },
    "9": {
      "Question": "Quelle fonction DAX permet de renvoyer la valeur distincte d'une colonne ?",
      "A": "DISTINCT",
      "B": "UNIQUE",
      "C": "FILTER",
      "D": "SELECT",
      "Reponse": "A"
    },
    "10": {
      "Question": "Quelle est la première étape pour se connecter à une nouvelle source de données dans Power BI ?",
      "A": "Get Data",
      "B": "Import Data",
      "C": "Load Data",
      "D": "Connect Data",
      "Reponse": "A"
    }
  }
}

PowerBi_2={
  "QCM_PowerBI_intermediaire": {
    "1": {
      "Question": "Quel type de relation doit être défini entre deux tables pour créer un modèle de données dans Power BI ?",
      "A": "Relation Plusieurs à Un (Many-to-One)",
      "B": "Relation Un à Un (One-to-One)",
      "C": "Relation Plusieurs à Plusieurs (Many-to-Many)",
      "D": "Relation Un à Plusieurs (One-to-Many)",
      "Reponse": "A"
    },
    "2": {
      "Question": "Comment créer une nouvelle colonne calculée dans Power BI Desktop ?",
      "A": "Utiliser DAX dans le Modèle de Données",
      "B": "Utiliser M Language dans Power Query",
      "C": "Utiliser le panneau de Visualisation",
      "D": "Utiliser le ruban d'Accueil",
      "Reponse": "A"
    },
    "3": {
      "Question": "Quelle est la différence principale entre les mesures et les colonnes calculées dans Power BI ?",
      "A": "Les mesures sont recalculées au niveau de la visualisation, tandis que les colonnes calculées sont stockées dans le modèle de données.",
      "B": "Les mesures sont stockées dans le modèle de données, tandis que les colonnes calculées sont recalculées au niveau de la visualisation.",
      "C": "Les mesures ne peuvent pas utiliser de fonctions DAX, contrairement aux colonnes calculées.",
      "D": "Les mesures sont utilisées uniquement pour les dates, tandis que les colonnes calculées peuvent être utilisées pour tout type de données.",
      "Reponse": "A"
    },
    "4": {
      "Question": "Quelle fonctionnalité de Power BI permet de créer des visualisations interactives pour les utilisateurs ?",
      "A": "Bookmarks",
      "B": "Drillthrough",
      "C": "Tooltips",
      "D": "Power Query",
      "Reponse": "A"
    },
    "5": {
      "Question": "Quelle visualisation serait la plus appropriée pour comparer les proportions de différentes catégories à un total ?",
      "A": "Pie Chart",
      "B": "Line Chart",
      "C": "Scatter Plot",
      "D": "Tree Map",
      "Reponse": "A"
    },
    "6": {
      "Question": "Quel type de visuel permet de montrer la distribution d'une mesure à travers plusieurs catégories dans Power BI ?",
      "A": "Histogram",
      "B": "Pie Chart",
      "C": "Bar Chart",
      "D": "Waterfall Chart",
      "Reponse": "A"
    },
    "7": {
      "Question": "Quelle est la meilleure manière de partager un rapport Power BI avec des collègues pour collaboration ?",
      "A": "Publier sur Power BI Service",
      "B": "Envoyer par email",
      "C": "Partager un fichier .pbix",
      "D": "Imprimer le rapport",
      "Reponse": "A"
    },
    "8": {
      "Question": "Quelle fonction DAX permet de calculer un total cumulé ?",
      "A": "CALCULATE",
      "B": "SUM",
      "C": "CUMULATE",
      "D": "TOTALYTD",
      "Reponse": "D"
    },
    "9": {
      "Question": "Comment afficher des données détaillées sous une visualisation de résumé dans Power BI ?",
      "A": "Utiliser la fonctionnalité Drillthrough",
      "B": "Utiliser la fonctionnalité Tooltips",
      "C": "Utiliser la fonctionnalité Filters",
      "D": "Utiliser la fonctionnalité Bookmarks",
      "Reponse": "A"
    },
    "10": {
      "Question": "Quelle visualisation est la meilleure pour analyser la contribution de chaque part au total global ?",
      "A": "Donut Chart",
      "B": "Bar Chart",
      "C": "Line Chart",
      "D": "Scatter Plot",
      "Reponse": "A"
    }
  }
}

PowerBi_3={
  "QCM_PowerBI_confirme": {
    "1": {
      "Question": "Quelle est la différence entre la fonction DAX 'ALL()' et 'REMOVEFILTERS()' ?",
      "A": "'ALL()' ignore les filtres sur toutes les colonnes spécifiées, tandis que 'REMOVEFILTERS()' ignore les filtres sur toutes les colonnes de la table.",
      "B": "'ALL()' ignore les filtres sur une seule colonne spécifiée, tandis que 'REMOVEFILTERS()' ignore les filtres sur toutes les colonnes spécifiées.",
      "C": "'ALL()' supprime tous les filtres du rapport, tandis que 'REMOVEFILTERS()' supprime uniquement les filtres de visualisation.",
      "D": "'ALL()' est utilisé uniquement pour les dates, tandis que 'REMOVEFILTERS()' peut être utilisé pour tout type de données.",
      "Reponse": "A"
    },
    "2": {
      "Question": "Comment optimiser les performances d'un rapport Power BI comportant de grandes quantités de données ?",
      "A": "Utiliser des agrégations et des résumés de données",
      "B": "Augmenter la mémoire de l'ordinateur",
      "C": "Utiliser des visuels plus complexes",
      "D": "Ajouter plus de filtres de visualisation",
      "Reponse": "A"
    },
    "3": {
      "Question": "Quelle est la principale utilisation de la fonction DAX 'EARLIER()' ?",
      "A": "Référencer la valeur d'une colonne dans une itération précédente",
      "B": "Retourner la première valeur d'une table",
      "C": "Calculer une valeur basée sur une condition",
      "D": "Créer des relations entre tables",
      "Reponse": "A"
    },
    "4": {
      "Question": "Quelle est la différence entre une 'table liée' et une 'table calculée' dans Power BI ?",
      "A": "Une 'table liée' est importée directement d'une source de données externe, tandis qu'une 'table calculée' est créée avec des formules DAX dans Power BI.",
      "B": "Une 'table liée' est créée avec des formules DAX, tandis qu'une 'table calculée' est importée directement d'une source de données externe.",
      "C": "Une 'table liée' ne peut pas être modifiée, tandis qu'une 'table calculée' peut être modifiée.",
      "D": "Une 'table liée' est utilisée pour les relations de données, tandis qu'une 'table calculée' est utilisée pour les mesures.",
      "Reponse": "A"
    },
    "5": {
      "Question": "Quel est l'avantage d'utiliser 'DirectQuery' par rapport à 'Import Data' dans Power BI ?",
      "A": "DirectQuery permet une actualisation en temps réel des données.",
      "B": "DirectQuery améliore la performance globale du rapport.",
      "C": "DirectQuery permet l'utilisation de plus de sources de données.",
      "D": "DirectQuery réduit la taille du fichier .pbix.",
      "Reponse": "A"
    },
    "6": {
      "Question": "Comment créer une relation plusieurs-à-plusieurs entre deux tables dans Power BI ?",
      "A": "Créer une table de pont (bridge table) entre les deux tables",
      "B": "Utiliser la fonction DAX 'RELATEDTABLE()'",
      "C": "Créer une relation directe entre les deux tables",
      "D": "Utiliser des colonnes calculées",
      "Reponse": "A"
    },
    "7": {
      "Question": "Quelle fonction DAX permet de créer des mesures dépendantes du contexte de filtre ?",
      "A": "CALCULATE",
      "B": "SUMX",
      "C": "FILTER",
      "D": "ALL",
      "Reponse": "A"
    },
    "8": {
      "Question": "Quelle fonctionnalité de Power BI permet de configurer des alertes pour les utilisateurs finaux ?",
      "A": "Data Alerts",
      "B": "Conditional Formatting",
      "C": "Power Query",
      "D": "Report Filters",
      "Reponse": "A"
    },
    "9": {
      "Question": "Comment publier un rapport Power BI sur un site SharePoint ?",
      "A": "Utiliser l'option 'Publish to Web' dans Power BI Service",
      "B": "Exporter le rapport en PDF et l'importer dans SharePoint",
      "C": "Intégrer le rapport en utilisant l'URL du rapport Power BI Service",
      "D": "Envoyer le fichier .pbix par email et demander aux utilisateurs de le charger",
      "Reponse": "A"
    },
    "10": {
      "Question": "Quelle est la fonctionnalité utilisée pour analyser les données d'un rapport Power BI avec Excel ?",
      "A": "Analyze in Excel",
      "B": "Export Data",
      "C": "Get Data",
      "D": "Import Data",
      "Reponse": "A"
    }
  }
}

"""#Machine Learning"""

Machine_Learning_1={
  "QCM_machine_learning_debutant": {
    "1": {
      "Question": "Quelle méthode est utilisée pour évaluer la performance d'un modèle de régression ?",
      "A": "Accuracy",
      "B": "Precision",
      "C": "RMSE (Root Mean Squared Error)",
      "D": "F1-score",
      "Reponse": "C"
    },
    "2": {
      "Question": "Quelle étape du processus de machine learning consiste à séparer les données en ensembles d'entraînement et de test ?",
      "A": "Feature engineering",
      "B": "Validation croisée",
      "C": "Prétraitement des données",
      "D": "Evaluation du modèle",
      "Reponse": "A"
    },
    "3": {
      "Question": "Quel algorithme de machine learning est utilisé pour la classification binaire ?",
      "A": "K-means",
      "B": "Decision Tree",
      "C": "PCA (Principal Component Analysis)",
      "D": "Linear Regression",
      "Reponse": "B"
    },
    "4": {
      "Question": "Quelle méthode de régularisation est souvent utilisée pour réduire le surajustement dans les modèles de régression linéaire ?",
      "A": "Dropout",
      "B": "Lasso",
      "C": "SVM (Support Vector Machine)",
      "D": "K-nearest neighbors",
      "Reponse": "B"
    },
    "5": {
      "Question": "Quelle métrique est utilisée pour évaluer la performance d'un modèle de classification binaire ?",
      "A": "Mean Absolute Error (MAE)",
      "B": "R-squared",
      "C": "Log Loss",
      "D": "Confusion Matrix",
      "Reponse": "C"
    },
    "6": {
      "Question": "Quel type de problème de machine learning vise à prédire une valeur continue ?",
      "A": "Classification",
      "B": "Clustering",
      "C": "Régression",
      "D": "Sélection de variables",
      "Reponse": "C"
    },
    "7": {
      "Question": "Quelle est la première étape recommandée lors de la construction d'un modèle de machine learning ?",
      "A": "Prétraitement des données",
      "B": "Feature engineering",
      "C": "Choix de l'algorithme",
      "D": "Evaluation du modèle",
      "Reponse": "B"
    },
    "8": {
      "Question": "Quel algorithme de machine learning est souvent utilisé pour imputer les valeurs manquantes dans un jeu de données ?",
      "A": "PCA (Principal Component Analysis)",
      "B": "K-means",
      "C": "Random Forest",
      "D": "K-nearest neighbors",
      "Reponse": "C"
    },
    "9": {
      "Question": "Quelle méthode de réduction de dimension est utilisée pour compresser les données en préservant au mieux leur variance ?",
      "A": "PCA (Principal Component Analysis)",
      "B": "LDA (Linear Discriminant Analysis)",
      "C": "K-means",
      "D": "Logistic Regression",
      "Reponse": "A"
    },
    "10": {
      "Question": "Quelle est l'utilité principale de la validation croisée dans le processus de machine learning ?",
      "A": "Evaluer la performance du modèle sur des données de test",
      "B": "Sélectionner les meilleures features pour le modèle",
      "C": "Evaluer la stabilité du modèle face à des variations dans les données",
      "D": "Augmenter la taille du jeu de données",
      "Reponse": "A"
    }
  }
}

Machine_Learning_2={
  "QCM_machine_learning_intermediaire": {
    "1": {
      "Question": "Quel algorithme est souvent utilisé pour la régression linéaire lorsque le nombre de features est élevé et qu'il y a multicollinéarité entre les features ?",
      "A": "Lasso",
      "B": "Ridge",
      "C": "ElasticNet",
      "D": "Decision Tree",
      "Reponse": "B"
    },
    "2": {
      "Question": "Quelle est la méthode utilisée pour améliorer la performance d'un modèle en ajustant les hyperparamètres ?",
      "A": "Feature selection",
      "B": "Optimisation bayésienne",
      "C": "Gradient boosting",
      "D": "Entraînement du modèle",
      "Reponse": "B"
    },
    "3": {
      "Question": "Quel algorithme de machine learning est souvent utilisé pour résoudre des problèmes de recommandation ?",
      "A": "SVM (Support Vector Machine)",
      "B": "K-means",
      "C": "Collaborative filtering",
      "D": "PCA (Principal Component Analysis)",
      "Reponse": "C"
    },
    "4": {
      "Question": "Quelle métrique est souvent utilisée pour évaluer la performance d'un modèle de clustering ?",
      "A": "Silhouette score",
      "B": "F1-score",
      "C": "R-squared",
      "D": "Log Loss",
      "Reponse": "A"
    },
    "5": {
      "Question": "Quelle est l'utilité principale de la régularisation dans les modèles de machine learning ?",
      "A": "Réduire le surapprentissage (overfitting)",
      "B": "Augmenter la précision du modèle",
      "C": "Réduire le temps de calcul",
      "D": "Stabiliser les prédictions",
      "Reponse": "A"
    },
    "6": {
      "Question": "Quelle méthode de clustering est basée sur la minimisation de la variance intra-cluster et la maximisation de la variance inter-cluster ?",
      "A": "K-means",
      "B": "DBSCAN",
      "C": "Hierarchical clustering",
      "D": "Mean-Shift clustering",
      "Reponse": "A"
    },
    "7": {
      "Question": "Quelle est la méthode utilisée pour réduire le temps de calcul lors de l'entraînement d'un modèle de machine learning ?",
      "A": "Batch normalization",
      "B": "Feature scaling",
      "C": "Parallelisation",
      "D": "Mini-batch gradient descent",
      "Reponse": "D"
    },
    "8": {
      "Question": "Quel algorithme de machine learning est adapté pour résoudre des problèmes de classification avec un grand nombre de classes ?",
      "A": "Random Forest",
      "B": "Naive Bayes",
      "C": "Multi-layer Perceptron",
      "D": "Logistic Regression",
      "Reponse": "C"
    },
    "9": {
      "Question": "Quel est le principal avantage des méthodes ensemblistes comme le Random Forest ?",
      "A": "Faible interprétabilité",
      "B": "Tendance au surapprentissage (overfitting)",
      "C": "Réduction de la variance",
      "D": "Faible précision",
      "Reponse": "C"
    },
    "10": {
      "Question": "Quelle est la méthode utilisée pour évaluer l'importance des features dans un modèle de machine learning ?",
      "A": "Confusion Matrix",
      "B": "Permutation Importance",
      "C": "AUC-ROC Curve",
      "D": "Precision-Recall Curve",
      "Reponse": "B"
    }
  }
}

Machine_Learning_3={
  "QCM_machine_learning_confirme": {
    "1": {
      "Question": "Quel est l'algorithme de deep learning utilisé pour le traitement des séquences de données ?",
      "A": "CNN (Convolutional Neural Network)",
      "B": "LSTM (Long Short-Term Memory)",
      "C": "PCA (Principal Component Analysis)",
      "D": "K-means",
      "Reponse": "B"
    },
    "2": {
      "Question": "Quelle est la méthode utilisée pour réduire le biais introduit par l'overfitting dans les modèles de deep learning ?",
      "A": "Data augmentation",
      "B": "Dropout",
      "C": "Batch normalization",
      "D": "Entraînement sur un GPU",
      "Reponse": "B"
    },
    "3": {
      "Question": "Quelle est la fonction d'activation souvent utilisée pour les couches de sortie d'un modèle de classification binaire ?",
      "A": "ReLU (Rectified Linear Unit)",
      "B": "Sigmoid",
      "C": "Tanh",
      "D": "Softmax",
      "Reponse": "B"
    },
    "4": {
      "Question": "Quel est l'algorithme utilisé pour optimiser les poids d'un réseau de neurones pendant l'apprentissage ?",
      "A": "Gradient Descent",
      "B": "Random Forest",
      "C": "K-means",
      "D": "PCA (Principal Component Analysis)",
      "Reponse": "A"
    },
    "5": {
      "Question": "Quelle méthode est utilisée pour sélectionner automatiquement les hyperparamètres optimaux d'un modèle de machine learning ?",
      "A": "Grid Search",
      "B": "Cross-validation",
      "C": "Optimisation bayésienne",
      "D": "Feature engineering",
      "Reponse": "C"
    },
    "6": {
      "Question": "Quelle est la technique utilisée pour encoder des variables catégorielles en utilisant plusieurs colonnes binaires ?",
      "A": "One-Hot Encoding",
      "B": "Label Encoding",
      "C": "Feature Scaling",
      "D": "PCA (Principal Component Analysis)",
      "Reponse": "A"
    },
    "7": {
      "Question": "Quelle est la méthode utilisée pour éviter la disparition du gradient dans les réseaux de neurones profonds ?",
      "A": "Dropout",
      "B": "Batch normalization",
      "C": "Weight initialization",
      "D": "ReLU (Rectified Linear Unit)",
      "Reponse": "B"
    },
    "8": {
      "Question": "Quelle est la technique utilisée pour évaluer la performance d'un modèle de régression en mesurant l'erreur moyenne de prédiction ?",
      "A": "R-squared",
      "B": "Mean Absolute Error (MAE)",
      "C": "Log Loss",
      "D": "Silhouette score",
      "Reponse": "B"
    },
    "9": {
      "Question": "Quel est le principal défi lors de l'utilisation de données non structurées dans un modèle de machine learning ?",
      "A": "Sélection des features",
      "B": "Prétraitement des données",
      "C": "Choix de l'algorithme",
      "D": "Interprétation des résultats",
      "Reponse": "B"
    },
    "10": {
      "Question": "Quelle est la méthode utilisée pour mesurer la distance entre les points dans l'espace des features lors de la classification par K-means ?",
      "A": "Euclidean distance",
      "B": "Manhattan distance",
      "C": "Hamming distance",
      "D": "Cosine similarity",
      "Reponse": "A"
    }
  }
}

"""Liste des domaines"""
domaines_dict = {
                 "python" : [Python_1,Python_2,Python_3],
                 "sql" : [SQL_0,SQL_2,SQL_3],
                 "powerBI" : [PowerBi_1,PowerBi_2,PowerBi_3],
                 "machine_learning" : [Machine_Learning_1,Machine_Learning_2,Machine_Learning_3]
                 }